### ISSUE TITLE
Sparkline Component doesn't work

### ISSUE THREAD

**Issue by doums10** [adrianhajdin/project_syncfusion_dashboard#17]
I dont have the Sparkline line on the Ecommerce view, anyone knows why?

<img width="1680" alt="Capture d’écran 2022-09-13 à 17 39 14" src="https://user-images.githubusercontent.com/24893051/190015293-34fbd9d5-f854-4f1f-b54e-16d36fe134c4.png">
<img width="744" alt="Capture d’écran 2022-09-13 à 17 39 59" src="https://user-images.githubusercontent.com/24893051/190015319-62023a9d-5c39-4d02-bc5e-e706a4270735.png">

**Comment by Pannu786** [comment]
Change **yName='y' to yName='yval'**     This should fix the issue.

**Comment by CGTones** [comment]
i couldn't get sparkline to render until i refactored it to a class component as shown here in the repo:

https://github.com/adrianhajdin/project_syncfusion_dashboard/blob/main/src/components/Charts/SparkLine.jsx

**Comment by Pannu786** [comment]
Can show us how was your function-based code?

**Comment by CGTones** [comment]
sry. my mistake. the issue i had was only triggered when resizing the browser window. nothing would display on resize. resolved upon refactoring to pure class component. but fwiw, here is the link to the commit history on my alt gh account

https://github.com/degenGenesis/dashboard/commit/b4dd1cee1276b251a4ab2d340731c454d03ca6f9

**Comment by doums10** [comment]
> Change **yName='y' to yName='yval'** This should fix the issue.

yes, its correct, thanks bro
