### ISSUE TITLE
GoPrimitiveDot Component doesn't work

### ISSUE THREAD

**Issue by sajeed11** [adrianhajdin/project_syncfusion_dashboard#39]
I've imported the GoPrimitiveDot component from react-icons/go to use it as the tutorial said, but it seems it doesn't exist in the previous folder. I guess there's a problem in depandecies version or something like that.

**Comment by HorseXInsectCoder** [comment]
GoPrimitiveDot no longer exists.

**Comment by sajeed11** [comment]
> GoPrimitiveDot no longer exists.

Thanks, man a lot I have replaced it with something else, ty again :3

**Comment by dilipgandham562** [comment]
> > GoPrimitiveDot no longer exists.
> 
> Thanks, man a lot I have replaced it with something else, ty again :3
can you tell the package you have replaced with

**Comment by dilipgandham562** [comment]
Can you tell the package you have replaced with

**Comment by sajeed11** [comment]
> Can you tell the package you have replaced with

@dilipgandham562 
Not the package, the same one, but I have replaced it with something similar by the same package.
You can search here to find something that @could help you  [https://react-icons.github.io/react-icons/]()

**Comment by JspBack** [comment]
I used GoDotFill , i think it is same as GoPrimitiveDot.

**Comment by marcianomatias** [comment]
Eu usei o GoDotFill e está funcionando.

**Comment by Obulesu12345** [comment]
Which version is using for goprimitivedot

**Comment by Fasel-Ergando** [comment]
Thanks but goPrimitiveDot does not work whyyyy???
